/**:
  ros__parameters:
    camera_name: rs  #description': 'camera unique name'
    #serial_no: '948122072396'          #description': 'choose device by serial number'
    pointcloud.enable: True    #description': '' 
    pointcloud.ordered_pc           : True    #description': ''
    pointcloud.stream_filter: 1        #description': 'texture stream for pointcloud'
    pointcloud.stream_index_filter: 0        #description': 'texture stream index for pointcloud'
    enable_sync: True    #description': ''                           
    align_depth.enable: True    #description': ''
    enable_pose                     : True    #description': ''
    unite_imu_method                : 2           #description': '[0-None, 1-copy, 2-linear_interpolation]'
    enable_gyro: True    #description': ''                           
    enable_accel: True    #description': ''   
    initial_reset: True    #description': ''    

    enable_depth                    : True      #description': 'enable depth stream'
    enable_color                    : True    #description': 'enable color stream'
    enable_infra1                   : True    #description': 'enable infra1 stream'
    enable_infra2                   : True    #description': 'enable infra2 stream'

    # usb_port_id                     : ''          #description': 'choose device by usb port id'
    # device_type                     : ''          #description': 'choose device by type'
    # config_file                     : ''          #description': 'yaml config file'
    # json_file_path                  : ''          #description': 'allows advanced configuration'
    # log_level                       : 'info'     #description': 'debug log level [DEBUG|INFO|WARN|ERROR|FATAL]'
    # output                          : 'screen'   #description': 'pipe node output [screen|log]'
    # depth_module.profile            : '0,0,0 '    #description': 'depth module profile'                           
    # enable_depth                    : True      #description': 'enable depth stream'
    # rgb_camera.profile              : '0,0,0 '    #description': 'color image width'
    # infra_rgb                       : False    #description': 'enable infra2 stream'
    # enable_fisheye1                 : True    #description': 'enable fisheye1 stream'
    # enable_fisheye2                 : True    #description': 'enable fisheye2 stream'
    # enable_confidence               : True    #description': 'enable depth stream'
    # gyro_fps                        : 0        #description': ''                           
    # accel_fps                       : 0        #description': ''                                                 
                           
    # pose_fps                        : 200      #description': ''                                                      
    colorizer.enable                : False    #description': ''
    clip_distance                   : -2.0      #description': ''                           
    # linear_accel_cov                : 0.01      #description': ''                           
    # initial_reset                   : False    #description': ''                           
    # allow_no_texture_points         : False    #description': ''                           
    # tf_publish_rate                 : 0.0     #description': 'Rate of publishing static_tf'
    # diagnostics_period              : 0.0    #description': 'Rate of publishing diagnostics. 0=Disabled'
    # decimation_filter.enable        : False    #description': 'Rate of publishing static_tf'
    # rosbag_filename                 : ''       #description': 'A realsense bagfile to run from as a device'
    # depth_module.exposure.1         : 7500    #description': 'Depth module first exposure value. Used for hdr_merge filter'
    # depth_module.gain.1             : 16    #description': 'Depth module first gain value. Used for hdr_merge filter'
    # depth_module.exposure.2         : 1    #description': 'Depth module second exposure value. Used for hdr_merge filter'
    # depth_module.gain.2             : 16    #description': 'Depth module second gain value. Used for hdr_merge filter'
    # depth_module.hdr_enabled        : False    #description': 'Depth module hdr enablement flag. Used for hdr_merge filter'
    # hdr_merge.enable                : False    #description': 'hdr_merge filter enablement flag'
    # wait_for_device_timeout         : -1.0    #description': 'Timeout for waiting for device to connect (Seconds)'
    # reconnect_timeout               : 6.0     #description': 'Timeout(seconds) between consequtive reconnection attempts'