
services:

  rs_driver: # Working  
    image: mvancleaver/realsense_ros:foxy
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile.realsense
    network_mode: host
    volumes:
      - /dev:/dev
      - ../../../config/params:/config
    privileged: true
    restart: unless-stopped
    command: ros2 launch realsense2_camera rs_launch.py camera_name:='rs_'s unite_imu_method:=2 align_depth.enable:=True enable_gyro:=true enable_accel:=true pointcloud.enable:=true pointcloud.stream_filter:=0 allow_no_texture_point:=true pointcloud.ordered_pc:=true pointcloud.stream_index_filter:=1
